All commits
klenitskays/taxi pull request #2
Opened 2024-02-26 14:55 UTC by klenitskays

First pull request

2024-02-26 16:50 UTC, yanzharov1 commented on pom.xml
> +		<groupId>org.springframework.boot</groupId>
Зачем использовать 3rd-party библиотеку в качестве parent?
Ее нужно переместить в блок зависимостей

2024-02-26 17:01 UTC, yanzharov1 commented on script.sql
> +CREATE TABLE driver
дупликат скрипта из liquibase

2024-02-26 17:04 UTC, yanzharov1 commented on src/main/java/com/example/driver/controller/DriverController.java
> +    private final DriverService driverService;
В проекте уже есть lombok. Можно использовать @RequiredArgsConstructor

2024-02-26 17:15 UTC, yanzharov1 commented on src/main/java/com/example/driver/controller/DriverController.java
> +    @GetMapping("/isAvailable")
нужно поправить нейминг
например findAvailableDrivers

2024-02-26 17:15 UTC, yanzharov1 commented on src/main/java/com/example/driver/controller/DriverController.java
> +        List<DriverDTO> driverDTOs = driverService.isAvailable().stream()
тот же комментарий

2024-02-26 17:16 UTC, yanzharov1 commented on src/main/java/com/example/driver/controller/DriverController.java
> +                .map(driver -> {
зачем нужен повторный маппинг?

2024-02-26 17:18 UTC, yanzharov1 commented on src/main/java/com/example/driver/controller/DriverController.java
> +        DriverDTO existingDriverDTO = driverService.readById(id);
эту логику лучше переместить в сервис

2024-02-26 17:23 UTC, yanzharov1 commented on src/main/java/com/example/driver/controller/DriverController.java
> +import com.example.driver.dto.DriverDTO;
Сервис не содержит всего функционала отсюда
![image](https://github.com/klenitskays/taxi/assets/89585010/1e3ab1cb-8498-47ef-a004-32b6bb7ec4e1)
Она будет добавлена позже?

2024-02-26 17:25 UTC, yanzharov1 commented on src/main/java/com/example/driver/impl/DriverServiceImpl/DriverServiceImpl.java
> +            return driverMapper.toDriverDTO(driver);
вероятно mapper предусматривает передачу null и это будет излишней проверкой

2024-02-26 17:29 UTC, yanzharov1 commented on src/main/java/com/example/driver/impl/DriverServiceImpl/DriverServiceImpl.java
> +        List<Driver> isAvailableDrivers = driverRepository.findByAvailableIsTrue();
про нейминг писал выше + можно избавиться от объявления переменной и сразу вызвать stream

2024-02-26 17:31 UTC, yanzharov1 commented on src/main/java/com/example/driver/impl/DriverServiceImpl/DriverServiceImpl.java
> +        driver.setRating(dto.getRating());
нужно использовать маппер

2024-02-26 17:33 UTC, yanzharov1 commented on src/main/java/com/example/driver/mapper/DriverMapper.java
> +@Mapper(componentModel = "spring")
нужно предусматривать тот случай когда dto и entity могут отличаться
для этого в Mapper есть соответствующие настройки
тем не менее опционально, в этом случае все будет работать

2024-02-26 17:41 UTC, yanzharov1 commented on src/main/resources/db/changelog/v-1.0/01-create-driver-table.sql
> +    id           INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
рекомендую почитать про то какие id могут быть в таблице и какие недостатки есть у автоинкрементируемых id

2024-02-26 17:42 UTC, yanzharov1 commented on src/test/java/com/example/driver/DriverApplicationTests.java
> +	void contextLoads() {
этот тест будет обновляться в дальнейшем?

2024-02-27 11:18 UTC, yanzharov1 commented on src/main/java/com/example/driver/dto/DriverDTO.java
> +import com.example.driver.entity.Driver;
DTO не может наследовать entity
иначе в твоем апи будет зависимость на слой взаимодействия с базой

2024-02-27 11:19 UTC, yanzharov1 commented on src/main/java/com/example/driver/entity/Driver.java
> +    private double latitude;
колонки в базе не nonnull но поля примитивного типа
потенциальный npe

2024-02-27 11:20 UTC, yanzharov1 commented on src/main/java/com/example/driver/impl/DriverServiceImpl/DriverServiceImpl.java
> +public class DriverServiceImpl implements DriverService {
Также кандидат на RequiredArgsConstructor

2024-02-27 11:21 UTC, yanzharov1 commented on src/main/java/com/example/driver/impl/DriverServiceImpl/DriverServiceImpl.java
> +        return driverMapper.toDriverDTO(driver);
зачем эти два метода?

2024-02-27 11:22 UTC, yanzharov1 commented on src/main/java/com/example/driver/impl/DriverServiceImpl/DriverServiceImpl.java
> +        if (optionalDriver.isPresent()) {
если используешь optional можно переписать через ifpresent -> else

2024-02-27 11:23 UTC, yanzharov1 commented on src/main/java/com/example/driver/impl/DriverServiceImpl/DriverServiceImpl.java
> +        if (optionalDriver.isPresent()) {
а еще лучше использовать Optional.map

2024-02-27 11:25 UTC, yanzharov1 commented on src/main/java/com/example/driver/service/DriverService.java
> +    @NotNull
возможно тебе понадобится более гибкая валидация с использованием валидатора в сервисе

2024-03-05 11:23 UTC, IvanKiselevichWork requested changes

2024-03-05 11:23 UTC, IvanKiselevichWork commented on driver-service/pom.xml
> +            <artifactId>spring-boot-starter-thymeleaf</artifactId>
А зачем в зависимостях thymeleaf?

2024-03-05 11:23 UTC, IvanKiselevichWork commented on driver-service/src/main/java/com/example/driver/controller/DriverController.java
> +@Data
А зачем над контроллером Data?

2024-03-05 11:23 UTC, IvanKiselevichWork commented on driver-service/src/main/java/com/example/driver/repo/DriverRepository.java
> +@Component
Можно убрать эту аннотацию

2024-03-05 11:23 UTC, IvanKiselevichWork commented on passenger-service/pom.xml
> +            <artifactId>spring-cloud-starter-openfeign</artifactId>
А зачем нужен openfeign?

2024-03-05 11:23 UTC, IvanKiselevichWork commented on passenger-service/src/main/java/com/example/passenger/repo/PassengerRepository.java
> +@Repository
Можно и эти две аннотации убрать

2024-03-07 10:49 UTC, IvanKiselevichWork requested changes

2024-03-07 10:49 UTC, IvanKiselevichWork commented on ride-service/src/main/java/com/example/rideservice/controller/RideController.java
> +    @GetMapping("/id/{id}")
Тут и в других похожих местах /id лишний, можно просто 
@GetMapping("/{id}")

2024-03-07 10:49 UTC, IvanKiselevichWork commented on ride-service/src/main/java/com/example/rideservice/entity/Ride.java
> +    public class Ride {
В этом классе что-то не то с отступами

2024-03-18 08:45 UTC, AbandonedScope requested changes

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/pom.xml
> +            <version>1.5.3.Final</version>
Версии зависимостей выносятся в тег proprties

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driver/controller/DriverController.java
> +        }
```suggestion
        if (drivers.isEmpty()) {
            return ResponseEntity.notFound().build();
        }
        
        return ResponseEntity.ok(drivers);
```

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driver/controller/DriverController.java
> +    public ResponseEntity<List<DriverDTO>> readByLastName(@RequestParam("lastName") String lastName) {
В таких случаях лучше вернуть просто пустой список, а не бросать not found

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driver/controller/DriverController.java
> +    public ResponseEntity<List<DriverDTO>> readByLastName(@RequestParam("lastName") String lastName) {
List<DriverDTO> - мы не возвращаем просто список, так будет сложно внести потом изменения какие-либо в ответ
Верни DriverListDto или что-нибудь похожее

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driver/controller/DriverController.java
> +    @GetMapping("/findAvailableDrivers")
Неправильно назван эндпоинт
Вот [тут](https://nordicapis.com/10-best-practices-for-naming-api-endpoints/) почитай

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driver/controller/DriverController.java
> +        }
```suggestion
        if (updatedDriverDTO == null) {
            return ResponseEntity.notFound().build();
        }
        
        return ResponseEntity.ok(updatedDriverDTO);
```

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driver/controller/DriverController.java
> +        DriverDTO updatedDriverDTO = driverService.update(dto, id);
Вообще, лучше возвращай Optional, а не null

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driver/controller/DriverController.java
> +    }
Возвращай сущность, которая была удалена

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driver/dto/DriverDTO.java
> +public class DriverDTO  {
Camelcase
DriverDTO -> DriverDto

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driver/entity/Driver.java
> +    @NotBlank(message = "Last name is required")
Такие валидационные проверки лучше навесь на dto-шки

2024-03-18 08:45 UTC, AbandonedScope commented on driver-service/src/main/resources/db/changelog/v-1.0/01-create-driver-table.sql
> +    last_name    VARCHAR(255),
Не слишком ли длинные имена?

2024-03-18 08:45 UTC, AbandonedScope commented on passenger-service/pom.xml
> +            <version>1.5.3.Final</version>
Версии в properties

2024-03-18 08:45 UTC, AbandonedScope commented on passenger-service/src/main/java/com/example/passenger/controller/PassengerController.java
> +
Много лишних пустых строк

2024-03-18 08:45 UTC, AbandonedScope commented on payment-service/src/main/resources/db/changelog/v-1.0/01-create-payment-table.sql
Полетело форматирование

2024-03-18 08:45 UTC, AbandonedScope commented on ride-service/src/main/java/com/example/rideservice/impl/RideServiceImpl.java
> +            // Handle case when no available drivers
Что за комментарии?

2024-03-18 08:45 UTC, AbandonedScope commented on ride-service/src/main/java/com/example/rideservice/impl/RideServiceImpl.java
> +    public RideDTO createRideWithDriver(Integer passengerId, Double startLatitude, Double startLongitude, Double destinationLatitude, Double destinationLongitude) {
Слишком много параметров в методе

2024-03-28 00:11 UTC, merged